### ISSUE TITLE
MCR

### ISSUE THREAD

**Issue by Grey-Wind** [Darknight123MC/Darknight123MC.github.io#1]
您好，由于MCR的仓库发不了issue，所以我在这里向您询问
请问我可以把您翻译的MCreator的中文tips(help)内容发送给官方吗
由于这项内容是您、[金子89(秦子引)](https://github.com/Fodoth-jinzi89)与[cdc12345](https://github.com/cdc12345)一同制作的，目前，我已经征得金子与cdc12345的同意，希望您也可以同意这项请求，谢谢
PR链接：https://github.com/MCreator/MCreator/pull/3409

**Comment by Darknight123MC** [comment]
完全同意
